I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 120, in script
    python:
  File "game/script.rpy", line 125, in <module>
    data = {'player_name': player_name, 'player_score': str(player_score)}
NameError: name 'player_name' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 120, in script
    python:
  File "G:\renpy-8.0.3-sdk\renpy\ast.py", line 1131, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "G:\renpy-8.0.3-sdk\renpy\python.py", line 1061, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 125, in <module>
    data = {'player_name': player_name, 'player_score': str(player_score)}
NameError: name 'player_name' is not defined

Windows-10-10.0.19044 AMD64
Ren'Py 8.0.3.22090809
striped_template 1.0
Sat May  6 23:47:37 2023
